<?php

  /**
   * Represents the Kendo UI RangeSlider widget. Inherits from Widget.
   * 
   * This class has been automatically generated by the class "classMaker.class.php" written by
   * Helmut Kemper <helmut.kemper@gmail.com> based into Kendo UI documents.
   * http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider
   * 
   */
  class KendoUiRangeSlider extends javascript
  {
    private $outputCStr;
    
    //---------- inicio codigo importante
    //
    //Coisas que não serão apagadas podem ser digitadas aqui dentro.
    //
    
    public function toHtmlOutput ( $htmlIdAStr, $extraAStr )
    {
      self::$mainHtmlCodeCStr .= "<input id=\"{$htmlIdAStr}\" {$extraAStr}>";
    }
    
    
    //---------- fim codigo importante
    
    public function toJavaScriptOutput ( $htmlIdALStr, $jsVarALStr = null )
    {
      if ( !is_null ( $jsVarALStr ) )
      {
        self::$mainJavaScriptCodeCStr .= "var {$jsVarALStr} = ";
      }
      self::$mainJavaScriptCodeCStr .= "$(\"#{$htmlIdALStr}\").KendoUiRangeSlider({\r\n";
      self::$mainJavaScriptCodeCStr .= self::toObject( javascript::$dataCArr );
      self::$mainJavaScriptCodeCStr .= "});\r\n";
      self::$dataCArr = null;
    }
    
    /**
     * The delta with which the value will change when the user presses the Page Up or Page Down key (the drag handle must be focused). Note: The allied <b><u>largeStep</u></b> will also set large tick for every large step.
     * @var $dataAX[ 'largeStep' ]: ( Number ) ( default: 5 )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-largeStep
     * @throws string type error
     */
    public function largeStep ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "largeStep" => $dataAX );
      
      if ( is_numeric ( $dataAX[ 'largeStep' ] ) )
      {
        parent::addData ( "largeStep", $dataAX[ 'largeStep' ] );
        unset ( $dataAX[ 'largeStep' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'largeStep' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::largeStep ( \$data[ 'largeStep' ] type must be 'Number'" );
      }
      
    }
    
    
    /**
     * The maximum value of the <strong>RangeSlider</strong>.
     * @var $dataAX[ 'max' ]: ( Number ) ( default: 10 )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-max
     * @throws string type error
     */
    public function max ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "max" => $dataAX );
      
      if ( is_numeric ( $dataAX[ 'max' ] ) )
      {
        parent::addData ( "max", $dataAX[ 'max' ] );
        unset ( $dataAX[ 'max' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'max' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::max ( \$data[ 'max' ] type must be 'Number'" );
      }
      
    }
    
    
    /**
     * The minimum value of the <strong>RangeSlider</strong>.
     * @var $dataAX[ 'min' ]: ( Number ) ( default: 0 )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-min
     * @throws string type error
     */
    public function min ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "min" => $dataAX );
      
      if ( is_numeric ( $dataAX[ 'min' ] ) )
      {
        parent::addData ( "min", $dataAX[ 'min' ] );
        unset ( $dataAX[ 'min' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'min' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::min ( \$data[ 'min' ] type must be 'Number'" );
      }
      
    }
    
    
    /**
     * F The orientation of a <strong>RangeSlider</strong>; <strong>"horizontal"</strong> or <strong>"vertical"</strong>.
     * @var $dataAX[ 'orientation' ]: ( String ) ( default: "horizontal" )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-orientation
     * @throws string type error
     */
    public function orientation ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "orientation" => $dataAX );
      
      if ( is_string ( $dataAX[ 'orientation' ] ) )
      {
        parent::addData ( "orientation", $dataAX[ 'orientation' ] );
        unset ( $dataAX[ 'orientation' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'orientation' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::orientation ( \$data[ 'orientation' ] type must be 'String'" );
      }
      
    }
    
    
    /**
     * The selection end value of the <strong>RangeSlider</strong>.
     * @var $dataAX[ 'selectionEnd' ]: ( Number )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-selectionEnd
     * @throws string type error
     */
    public function selectionEnd ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "selectionEnd" => $dataAX );
      
      if ( is_numeric ( $dataAX[ 'selectionEnd' ] ) )
      {
        parent::addData ( "selectionEnd", $dataAX[ 'selectionEnd' ] );
        unset ( $dataAX[ 'selectionEnd' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'selectionEnd' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::selectionEnd ( \$data[ 'selectionEnd' ] type must be 'Number'" );
      }
      
    }
    
    
    /**
     * The selection start value of the <strong>RangeSlider</strong>.
     * @var $dataAX[ 'selectionStart' ]: ( Number )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-selectionStart
     * @throws string type error
     */
    public function selectionStart ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "selectionStart" => $dataAX );
      
      if ( is_numeric ( $dataAX[ 'selectionStart' ] ) )
      {
        parent::addData ( "selectionStart", $dataAX[ 'selectionStart' ] );
        unset ( $dataAX[ 'selectionStart' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'selectionStart' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::selectionStart ( \$data[ 'selectionStart' ] type must be 'Number'" );
      }
      
    }
    
    
    /**
     * The small step value of the <strong>RangeSlider</strong>. The underlying value will be changed when the end user (1) clicks on the increase or decrease buttons of the <strong>RangeSlider</strong>, (2) presses the arrow keys (the drag handle must be focused), or (3) drags the drag handle.
     * @var $dataAX[ 'smallStep' ]: ( Number ) ( default: 1 )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-smallStep
     * @throws string type error
     */
    public function smallStep ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "smallStep" => $dataAX );
      
      if ( is_numeric ( $dataAX[ 'smallStep' ] ) )
      {
        parent::addData ( "smallStep", $dataAX[ 'smallStep' ] );
        unset ( $dataAX[ 'smallStep' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'smallStep' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::smallStep ( \$data[ 'smallStep' ] type must be 'Number'" );
      }
      
    }
    
    
    /**
     * Denotes the location of the tick marks in the <strong>RangeSlider</strong>. The available options are:
     * Tick marks are located on the top of the horizontal widget or on the left of the vertical widget.
     * Tick marks are located on the bottom of the horizontal widget or on the right side of the vertical widget.
     * <b>"both"</b> - Tick marks are located on both sides of the widget.
     * <b>"none"</b> - Tick marks are not visible.
     * @var $dataAX[ 'tickPlacement' ]: ( String ) ( default: "both" )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-tickPlacement
     * @throws string type error
     */
    public function tickPlacement ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "tickPlacement" => $dataAX );
      
      if ( is_string ( $dataAX[ 'tickPlacement' ] ) )
      {
        parent::addData ( "tickPlacement", $dataAX[ 'tickPlacement' ] );
        unset ( $dataAX[ 'tickPlacement' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'tickPlacement' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::tickPlacement ( \$data[ 'tickPlacement' ] type must be 'String'" );
      }
      
    }
    
    
    /**
     * Configuration of the <strong>RangeSlider</strong> tooltip.
     * @var $dataAX[ 'tooltip' ]: ( Object )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-tooltip
     * 
     * Disables (<strong>false</strong>) or enables (<strong>true</strong>) the tooltip of the <strong>RangeSlider</strong>.
     * @var $dataAX[ 'tooltip' ][ 'enabled' ]: ( Boolean ) ( default: true )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-tooltip.enabled
     * 
     * Format string for the text of the tooltip. Note: The applied format will also influence the appearance of the <strong>RangeSlider</strong> tick labels.
     * @var $dataAX[ 'tooltip' ][ 'format' ]: ( String ) ( default: "{0}" )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-tooltip.format
     * 
     * Template of the tooltip.
     * @var $dataAX[ 'tooltip' ][ 'template' ]: ( String )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider#configuration-tooltip.template
     * @throws string type error
     */
    public function tooltip ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "tooltip" => $dataAX );
      
      if ( is_bool ( $dataAX[ 'tooltip' ][ 'enabled' ] ) )
      {
        parent::addData ( "tooltip.enabled", $dataAX[ 'tooltip' ][ 'enabled' ] );
        unset ( $dataAX[ 'tooltip' ][ 'enabled' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'tooltip' ][ 'enabled' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::tooltip ( \$data[ 'tooltip' ][ 'enabled' ] type must be 'Boolean'" );
      }
      
      if ( is_string ( $dataAX[ 'tooltip' ][ 'format' ] ) )
      {
        parent::addData ( "tooltip.format", $dataAX[ 'tooltip' ][ 'format' ] );
        unset ( $dataAX[ 'tooltip' ][ 'format' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'tooltip' ][ 'format' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::tooltip ( \$data[ 'tooltip' ][ 'format' ] type must be 'String'" );
      }
      
      if ( is_string ( $dataAX[ 'tooltip' ][ 'template' ] ) )
      {
        parent::addData ( "tooltip.template", $dataAX[ 'tooltip' ][ 'template' ] );
        unset ( $dataAX[ 'tooltip' ][ 'template' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'tooltip' ][ 'template' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::tooltip ( \$data[ 'tooltip' ][ 'template' ] type must be 'String'" );
      }
      
      if ( is_array ( $dataAX[ 'tooltip' ] ) )
      {
        parent::addData ( "tooltip", $dataAX[ 'tooltip' ] );
        unset ( $dataAX[ 'tooltip' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'tooltip' ] ) )
      {
        throw new Exception ( "Type error - KendoUiRangeSlider::tooltip ( \$data[ 'tooltip' ] type must be 'Object'" );
      }
      
    }
    
    
  }