<?php

  /**
   * Represents the Kendo UI Splitter widget. Inherits from Widget.
   * 
   * This class has been automatically generated by the class "classMaker.class.php" written by
   * Helmut Kemper <helmut.kemper@gmail.com> based into Kendo UI documents.
   * http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter
   * Important: This method does not remove the widget element from DOM.
   */
  class KendoUiSplitter extends javascript
  {
    private $outputCStr;
    
    //---------- inicio codigo importante
    //
    //Coisas que não serão apagadas podem ser digitadas aqui dentro.
    //
    
    public function toHtmlOutput ( $htmlIdAStr, $extraAStr )
    {
      self::$mainHtmlCodeCStr .= "<input id=\"{$htmlIdAStr}\" {$extraAStr}>";
    }
    
    
    //---------- fim codigo importante
    
    public function toJavaScriptOutput ( $htmlIdALStr, $jsVarALStr = null )
    {
      if ( !is_null ( $jsVarALStr ) )
      {
        self::$mainJavaScriptCodeCStr .= "var {$jsVarALStr} = ";
      }
      self::$mainJavaScriptCodeCStr .= "$(\"#{$htmlIdALStr}\").KendoUiSplitter({\r\n";
      self::$mainJavaScriptCodeCStr .= self::toObject( javascript::$dataCArr );
      self::$mainJavaScriptCodeCStr .= "});\r\n";
      self::$dataCArr = null;
    }
    
    /**
     * Specifies the orientation of the widget. Supported values are <em>"horizontal"</em> and <em>"vertical"</em>.
     * @var $dataAX[ 'orientation' ]: ( String ) ( default: "horizontal" )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-orientation
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;orientation: "vertical"<br>});<br>&lt;/script&gt;
     * @endcode
     * @throws string type error
     */
    public function orientation ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "orientation" => $dataAX );
      
      if ( is_string ( $dataAX[ 'orientation' ] ) )
      {
        parent::addData ( "orientation", $dataAX[ 'orientation' ] );
        unset ( $dataAX[ 'orientation' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'orientation' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::orientation ( \$data[ 'orientation' ] type must be 'String'" );
      }
      
    }
    
    
    /**
     * An array of pane definitions.
     * @var $dataAX[ 'panes' ]: ( Array )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes
     * 
     * Specifies whether a pane is initially collapsed (<strong>true</strong>) or expanded (<strong>true</strong>).
     * @var $dataAX[ 'panes' ][ 'collapsed' ]: ( Boolean ) ( default: false )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.collapsed
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies the size of a collapsible pane when collapsed, defined as pixels (i.e. "200px") or as a percentage (i.e. "50%"). When the pane is collapsed a <strong>.k-state-collapsed</strong> class is added to it to ease its styling. Note: This value must not exceed <strong>panes.max</strong> or be less then <strong>panes.min</strong>.
     * @var $dataAX[ 'panes' ][ 'collapsedSize' ]: ( String ) ( default: false )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.collapsedSize
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies whether a pane is collapsible (<strong>true</strong>) or not collapsible (<strong>false</strong>).
     * @var $dataAX[ 'panes' ][ 'collapsible' ]: ( Boolean ) ( default: true )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.collapsible
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies the URL from which to load the content of a pane.
     * @var $dataAX[ 'panes' ][ 'contentUrl' ]: ( String ) ( default: true )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.contentUrl
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies the maximum size of a pane defined as pixels (i.e. "200px") or as a percentage (i.e. "50%"). The size of a resized pane cannot exceed the defined maximum size.
     * @var $dataAX[ 'panes' ][ 'max' ]: ( String )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.max
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies the minimum size of a pane defined as pixels (i.e. "200px") or as a percentage (i.e. "50%"). The size of a resized pane cannot be less than the defined minimum size.
     * @var $dataAX[ 'panes' ][ 'min' ]: ( String )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.min
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies whether a pane is resizable (<strong>true</strong>) or not resizable (<strong>false</strong>).
     * @var $dataAX[ 'panes' ][ 'resizable' ]: ( Boolean )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.resizable
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies whether a pane is scrollable (<strong>true</strong>) or not scrollable (<strong>false</strong>).
     * @var $dataAX[ 'panes' ][ 'scrollable' ]: ( Boolean )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.scrollable
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * 
     * Specifies the size of a pane defined as pixels (i.e. "200px") or as a percentage (i.e. "50%"). It is recommended that one pane is left without size in order to compensate for changes in the viewport size. Note: This value must not exceed <strong>panes.max</strong> or be less then <strong>panes.min</strong>.
     * @var $dataAX[ 'panes' ][ 'size' ]: ( String )
     * @see http://docs.telerik.com/kendo-ui/api/javascript/ui/splitter#configuration-panes.size
     * 
     * @code
       &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { collapsed: true } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true, collapsedSize: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { collapsible: true }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ {}, { contentUrl: "http://www.telerik.com/" } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { max: "200px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { min: "100px" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { resizable: false }, { resizable: false } ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { scrollable: false }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @code
        &lt;div id="splitter"&gt;<br>&nbsp;&lt;div&gt;Pane A&lt;/div&gt;<br>&nbsp;&lt;div&gt;Pane B&lt;/div&gt;<br>&lt;/div&gt;<br>&lt;script&gt;<br>$("#splitter").kendoSplitter({<br>&nbsp;panes: [ { size: "10%" }, {} ]<br>});<br>&lt;/script&gt;
     * @endcode
     * @throws string type error
     */
    public function panes ( $dataAX )
    {
      if ( !is_string ( $this->outputCStr ) )
      {
        $this->outputCStr = '';
      }
      
      $dataAX = array ( "panes" => $dataAX );
      
      if ( is_bool ( $dataAX[ 'panes' ][ 'collapsed' ] ) )
      {
        parent::addData ( "panes.collapsed", $dataAX[ 'panes' ][ 'collapsed' ] );
        unset ( $dataAX[ 'panes' ][ 'collapsed' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'collapsed' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'collapsed' ] type must be 'Boolean'" );
      }
      
      if ( is_string ( $dataAX[ 'panes' ][ 'collapsedSize' ] ) )
      {
        parent::addData ( "panes.collapsedSize", $dataAX[ 'panes' ][ 'collapsedSize' ] );
        unset ( $dataAX[ 'panes' ][ 'collapsedSize' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'collapsedSize' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'collapsedSize' ] type must be 'String'" );
      }
      
      if ( is_bool ( $dataAX[ 'panes' ][ 'collapsible' ] ) )
      {
        parent::addData ( "panes.collapsible", $dataAX[ 'panes' ][ 'collapsible' ] );
        unset ( $dataAX[ 'panes' ][ 'collapsible' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'collapsible' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'collapsible' ] type must be 'Boolean'" );
      }
      
      if ( is_string ( $dataAX[ 'panes' ][ 'contentUrl' ] ) )
      {
        parent::addData ( "panes.contentUrl", $dataAX[ 'panes' ][ 'contentUrl' ] );
        unset ( $dataAX[ 'panes' ][ 'contentUrl' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'contentUrl' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'contentUrl' ] type must be 'String'" );
      }
      
      if ( is_string ( $dataAX[ 'panes' ][ 'max' ] ) )
      {
        parent::addData ( "panes.max", $dataAX[ 'panes' ][ 'max' ] );
        unset ( $dataAX[ 'panes' ][ 'max' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'max' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'max' ] type must be 'String'" );
      }
      
      if ( is_string ( $dataAX[ 'panes' ][ 'min' ] ) )
      {
        parent::addData ( "panes.min", $dataAX[ 'panes' ][ 'min' ] );
        unset ( $dataAX[ 'panes' ][ 'min' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'min' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'min' ] type must be 'String'" );
      }
      
      if ( is_bool ( $dataAX[ 'panes' ][ 'resizable' ] ) )
      {
        parent::addData ( "panes.resizable", $dataAX[ 'panes' ][ 'resizable' ] );
        unset ( $dataAX[ 'panes' ][ 'resizable' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'resizable' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'resizable' ] type must be 'Boolean'" );
      }
      
      if ( is_bool ( $dataAX[ 'panes' ][ 'scrollable' ] ) )
      {
        parent::addData ( "panes.scrollable", $dataAX[ 'panes' ][ 'scrollable' ] );
        unset ( $dataAX[ 'panes' ][ 'scrollable' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'scrollable' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'scrollable' ] type must be 'Boolean'" );
      }
      
      if ( is_string ( $dataAX[ 'panes' ][ 'size' ] ) )
      {
        parent::addData ( "panes.size", $dataAX[ 'panes' ][ 'size' ] );
        unset ( $dataAX[ 'panes' ][ 'size' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ][ 'size' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ][ 'size' ] type must be 'String'" );
      }
      
      if ( is_array ( $dataAX[ 'panes' ] ) )
      {
        parent::addData ( "panes", $dataAX[ 'panes' ] );
        unset ( $dataAX[ 'panes' ] );
        parent::garbageCollector ( $dataAX );
      }
      else if ( isset ( $dataAX[ 'panes' ] ) )
      {
        throw new Exception ( "Type error - KendoUiSplitter::panes ( \$data[ 'panes' ] type must be 'Array'" );
      }
      
    }
    
    
  }